# on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gitactionsacr.azurecr.io
        username: ${{ secrets.acr_gitactionsacr_username }}
        password: ${{ secrets.acr_gitactionsacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t gitactionsacr.azurecr.io/tfakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push gitactionsacr.azurecr.io/tfakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_tfakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep gitactions | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace gitactions`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: gitactions
        container-registry-url: gitactionsacr.azurecr.io
        container-registry-username: ${{ secrets.acr_gitactionsacr_username }}
        container-registry-password: ${{ secrets.acr_gitactionsacr_password }}
        secret-name: tfaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: gitactions
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          gitactionsacr.azurecr.io/tfakscluster:${{ github.sha }}
        imagepullsecrets: |
          tfaksclusterdockerauth
